## Step 1 — Load and understand the data

In [32]:
import pandas as pd
df = pd.read_csv("Bassac_01.csv", nrows=3000)
df

                  Date    WL
0     19/06/2020 12:00  1.18
1     19/06/2020 12:15  1.16
2     19/06/2020 12:30  1.14
3     19/06/2020 12:45  1.12
4     19/06/2020 13:00  1.10
...                ...   ...
2995  20/07/2020 16:45  1.34
2996  20/07/2020 17:00  1.32
2997  20/07/2020 17:15  1.33
2998  20/07/2020 17:30  1.32
2999  20/07/2020 17:45  1.32

[3000 rows x 2 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3000 non-null   str
 1   WL      3000 non-null   float64
dtypes: float64(1), str(1)
memory usage: 47.0 KB

In [4]:
df.isnull().sum()

Date    0
WL      0
dtype: int64

In [5]:
df["Date"] = pd.to_datetime(
    df["Date"],
    dayfirst=True
)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3000 non-null   datetime64[us]
 1   WL      3000 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 47.0 KB

In [33]:
df = df.sort_values("Date").reset_index(drop=True)

In [34]:
df

                  Date    WL
0     01/07/2020 00:00  1.18
1     01/07/2020 00:15  1.16
2     01/07/2020 00:30  1.14
3     01/07/2020 00:45  1.14
4     01/07/2020 01:00  1.13
...                ...   ...
2995  30/06/2020 22:45  1.25
2996  30/06/2020 23:00  1.24
2997  30/06/2020 23:15  1.22
2998  30/06/2020 23:30  1.21
2999  30/06/2020 23:45  1.19

[3000 rows x 2 columns]

In [9]:
df.duplicated().sum()

np.int64(0)

## Step 2: Create the target variable

In [10]:
# Target the water lavel we want to predict
df["target"] = df["WL"].shift(-1)

#Drop NaN of the target column
df = df.dropna(subset=["target"])
df

                    Date    WL  target
0    2020-06-19 12:00:00  1.18    1.16
1    2020-06-19 12:15:00  1.16    1.14
2    2020-06-19 12:30:00  1.14    1.12
3    2020-06-19 12:45:00  1.12    1.10
4    2020-06-19 13:00:00  1.10    1.08
...                  ...   ...     ...
2994 2020-07-20 16:30:00  1.35    1.34
2995 2020-07-20 16:45:00  1.34    1.32
2996 2020-07-20 17:00:00  1.32    1.33
2997 2020-07-20 17:15:00  1.33    1.32
2998 2020-07-20 17:30:00  1.32    1.32

[2999 rows x 3 columns]

## Step3 Create Lag feature

In [11]:
df["lag_2"] = df["WL"].shift(2)
df["lag_4"] = df["WL"].shift(4)
df["lag_8"] = df["WL"].shift(8)
df["lag_12"] = df["WL"].shift(12)
df["lag_24"] = df["WL"].shift(24)

In [12]:
df

                    Date    WL  target  lag_2  lag_4  lag_8  lag_12  lag_24
0    2020-06-19 12:00:00  1.18    1.16    NaN    NaN    NaN     NaN     NaN
1    2020-06-19 12:15:00  1.16    1.14    NaN    NaN    NaN     NaN     NaN
2    2020-06-19 12:30:00  1.14    1.12   1.18    NaN    NaN     NaN     NaN
3    2020-06-19 12:45:00  1.12    1.10   1.16    NaN    NaN     NaN     NaN
4    2020-06-19 13:00:00  1.10    1.08   1.14   1.18    NaN     NaN     NaN
...                  ...   ...     ...    ...    ...    ...     ...     ...
2994 2020-07-20 16:30:00  1.35    1.34   1.38   1.39   1.44    1.50    1.49
2995 2020-07-20 16:45:00  1.34    1.32   1.36   1.39   1.43    1.48    1.51
2996 2020-07-20 17:00:00  1.32    1.33   1.35   1.38   1.41    1.48    1.53
2997 2020-07-20 17:15:00  1.33    1.32   1.34   1.36   1.39    1.45    1.55
2998 2020-07-20 17:30:00  1.32    1.32   1.32   1.35   1.39    1.44    1.55

[2999 rows x 8 columns]